### ISSUE TITLE
Register word should not be reserved

### ISSUE THREAD

**Issue by vit9696** [d0c-s4vage/pfp#25]
010 Editor does let you create variables with "register" names. pfp does not and errors on that.

**Comment by ghost** [comment]
can you give a specific example? like the code youre attempting to run that reproduces the error?

**Comment by vit9696** [comment]
At the time I reported the issue it was no more complex than:
int register;

**Comment by d0c-s4vage** [comment]
This was actually problem in py010parser, and was fixed with: d0c-s4vage/py010parser/issues/7.

Thanks for reporting it!

**Comment by vit9696** [comment]
@d0c-s4vage I am currently rechecking the fixes (thanks a lot for them), and this is still broken.
`int register;` will produce an error. I suggest this to be reopened.

Update: errrng, wait. Why do I still have the 14th version. Investigating at the moment.

**Comment by d0c-s4vage** [comment]
I haven't pushed to pypi yet

**Comment by d0c-s4vage** [comment]
and I just barely merged everything into the master branch - should be v0.1.15 now in the master branch

**Comment by vit9696** [comment]
Correct, have just installed things manually and the bug is fixed.

**Comment by d0c-s4vage** [comment]
btw, I made #pfp on irc, might be easier to chat there

**Comment by d0c-s4vage** [comment]
thanks for all the bug reports - I really appreciate the help!

**Comment by d0c-s4vage** [comment]
*freenode irc
